In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model

2025-04-09 10:54:47.250174: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-09 10:54:47.263305: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1744196087.278035  146830 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744196087.282497  146830 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1744196087.293894  146830 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # Disable GPU

import tensorflow as tf
print("Running on CPU:", tf.config.list_physical_devices('GPU'))

Running on CPU: []


2025-04-09 10:54:51.640555: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2025-04-09 10:54:51.640589: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:167] env: CUDA_VISIBLE_DEVICES="-1"
2025-04-09 10:54:51.640595: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:170] CUDA_VISIBLE_DEVICES is set to -1 - this hides all GPUs from CUDA
2025-04-09 10:54:51.640603: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:178] verbose logging is disabled. Rerun with verbose logging (usually --v=1 or --vmodule=cuda_diagnostics=1) to get more diagnostic output from this module
2025-04-09 10:54:51.640608: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:183] retrieving CUDA diagnostic information for host: hela
2025-04-09 10:54:51.640609: I external/local_xla/xla/stream_executor/cuda/cuda_dia

In [3]:
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available: 0


In [5]:
import numpy as np
import os

X_test = np.load( "/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/Task_1_scene_level/task1_X_test.npy")
y_test = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/Task_1_scene_level/task1_y_test.npy")
print(X_test.shape)
print(y_test.shape)

(2997, 224, 224, 3)
(2997, 3)


In [6]:
from tensorflow.keras.models import load_model

# Load model without compiling (since you're only using it for prediction)
model = load_model(
    "/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/VGG16/Models/retrained_model_with_f1.h5",
    compile=False
)


In [7]:
predictions = model.predict(X_test)

94/94 ━━━━━━━━━━━━━━━━━━━━ 53s 555ms/step


In [8]:
predicted_classes = np.argmax(predictions, axis=1)

print(predicted_classes[:10])

[1 0 0 0 0 0 0 0 0 2]


In [16]:
# print(y_test[:100])
for i in y_test:
    if i[1] == 1.0:
        print(i)
        print("Yes")
        break

# y_test_new= y_test

[0. 1. 0.]
Yes


In [17]:
y_test_labels = np.argmax(y_test, axis=1)

In [18]:
y_test_labels

array([0, 0, 0, ..., 2, 2, 2])

In [19]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report

# Convert model predictions to class labels
y_pred_labels = np.argmax(predictions, axis=1)

# Now compute accuracy
test_accuracy = accuracy_score(y_test_labels, y_pred_labels)
report= classification_report(y_test_labels, y_pred_labels, target_names=['Class 0', 'Class 1','Class 2'], output_dict=True)
print(report)
print(f"Test Accuracy: {test_accuracy:.4f}")
print(f"macro avg f1-score: {report['macro avg']['f1-score']:.4f}")


{'Class 0': {'precision': 0.8075253256150506, 'recall': 0.58004158004158, 'f1-score': 0.6751361161524501, 'support': 962}, 'Class 1': {'precision': 0.8998875140607424, 'recall': 0.8290155440414507, 'f1-score': 0.8629989212513485, 'support': 965}, 'Class 2': {'precision': 0.7417078334509527, 'recall': 0.9822429906542056, 'f1-score': 0.8451950140731805, 'support': 1070}, 'accuracy': 0.8038038038038038, 'macro avg': {'precision': 0.8163735577089152, 'recall': 0.7971000382457455, 'f1-score': 0.7944433504923264, 'support': 2997}, 'weighted avg': {'precision': 0.8137664985328042, 'recall': 0.8038038038038038, 'f1-score': 0.7963408634649688, 'support': 2997}}
Test Accuracy: 0.8038
macro avg f1-score: 0.7944


In [20]:
model_labelled = load_model(
    "/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/VGG16/Models/vgg16_modelScene_final.h5",
    compile=False
)

In [21]:
predictions_labelled = model_labelled.predict(X_test)

94/94 ━━━━━━━━━━━━━━━━━━━━ 61s 649ms/step


In [22]:
predicted_classes_labelled = np.argmax(predictions_labelled, axis=1)
print(predicted_classes_labelled[:10])

[1 0 2 2 2 0 2 2 0 2]


In [23]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report

# Convert model predictions to class labels
y_pred_labels_labelled = np.argmax(predictions_labelled, axis=1)
# Now compute accuracy
test_accuracy_labelled = accuracy_score(y_test_labels, y_pred_labels_labelled)
report_labelled= classification_report(y_test_labels, y_pred_labels_labelled, target_names=['Class 0', 'Class 1','Class 2'], output_dict=True)
print(report_labelled)
print(f"Test Accuracy: {test_accuracy_labelled:.4f}")
print(f"macro avg f1-score: {report_labelled['macro avg']['f1-score']:.4f}")


{'Class 0': {'precision': 0.7119815668202765, 'recall': 0.3212058212058212, 'f1-score': 0.4426934097421203, 'support': 962}, 'Class 1': {'precision': 0.9097035040431267, 'recall': 0.6994818652849741, 'f1-score': 0.7908611599297012, 'support': 965}, 'Class 2': {'precision': 0.585941790225151, 'recall': 0.997196261682243, 'f1-score': 0.7381528882739538, 'support': 1070}, 'accuracy': 0.684351017684351, 'macro avg': {'precision': 0.7358756203628514, 'recall': 0.6726279827243461, 'f1-score': 0.6572358193152584, 'support': 2997}, 'weighted avg': {'precision': 0.7306466013425541, 'recall': 0.684351017684351, 'f1-score': 0.6602855088278985, 'support': 2997}}
Test Accuracy: 0.6844
macro avg f1-score: 0.6572
