In [2]:

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.utils import to_categorical
# import matplotlib.pyplot as plt


2025-03-30 10:48:57.507091: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-30 10:48:58.670199: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1743331739.031039  429101 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1743331739.158642  429101 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1743331739.918247  429101 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [3]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # Disable GPU

import tensorflow as tf
print("Running on CPU:", tf.config.list_physical_devices('GPU'))

Running on CPU: []


2025-03-30 10:51:17.701366: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2025-03-30 10:51:17.701407: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:167] env: CUDA_VISIBLE_DEVICES="-1"
2025-03-30 10:51:17.701417: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:170] CUDA_VISIBLE_DEVICES is set to -1 - this hides all GPUs from CUDA
2025-03-30 10:51:17.701425: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:178] verbose logging is disabled. Rerun with verbose logging (usually --v=1 or --vmodule=cuda_diagnostics=1) to get more diagnostic output from this module
2025-03-30 10:51:17.701431: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:183] retrieving CUDA diagnostic information for host: hela
2025-03-30 10:51:17.701436: I external/local_xla/xla/stream_executor/cuda/cuda_dia

In [4]:
model = load_model("/home/sombit-ng-nonadm/vaibhav_intern_pg/CS230Project/vgg16_modelScene_final.h5")


In [5]:

X_labeled = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/CS230Project/Task_1_scene_level/X_labeled.npy", mmap_mode='r')
y_labeled = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/CS230Project/Task_1_scene_level/y_labeled.npy", mmap_mode='r')
X_unlabeled = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/CS230Project/Task_1_scene_level/X_unlabeled.npy", mmap_mode='r')



In [6]:
# Get predictions
predictions = model.predict(X_unlabeled)

# Display first 5 predictions
print("First 5 predictions (raw probabilities):")
print(predictions[:5])

# Convert to pseudo-labels
pseudo_labels = np.argmax(predictions, axis=1)

# Display first 5 pseudo-labels
print("First 5 pseudo-labels (predicted class indices):")
print(pseudo_labels[:5])


380/380 ━━━━━━━━━━━━━━━━━━━━ 226s 592ms/step
First 5 predictions (raw probabilities):
[[1.6287129e-36 0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [1.2251493e-25 1.0625141e-24 1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]
First 5 pseudo-labels (predicted class indices):
[2 2 2 2 2]


In [7]:
print("First 5 predictions (raw probabilities):")
print(predictions[1000:1500])

# Convert to pseudo-labels
pseudo_labels = np.argmax(predictions, axis=1)

# Display first 5 pseudo-labels
print("First 5 pseudo-labels (predicted class indices):")
print(pseudo_labels[1000:1500])


First 5 predictions (raw probabilities):
[[0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [2.3128227e-05 9.9997687e-01 2.3749139e-12]
 [9.9601871e-01 3.9812503e-03 6.8702763e-09]
 ...
 [1.2509788e-08 1.0000000e+00 1.0641938e-08]
 [4.0485081e-03 1.4840646e-01 8.4754509e-01]
 [3.5403588e-01 6.4591330e-01 5.0830287e-05]]
First 5 pseudo-labels (predicted class indices):
[2 1 0 2 2 2 2 2 2 0 2 2 2 2 0 2 2 1 0 2 1 2 2 2 2 2 1 2 2 2 0 2 2 2 2 1 2
 1 1 2 2 2 1 2 2 1 2 2 2 2 2 0 1 0 2 2 0 2 2 2 2 1 2 0 1 0 2 2 0 2 2 2 1 2
 0 1 2 2 2 0 2 2 2 2 2 2 2 1 2 1 2 2 2 1 2 2 0 2 2 2 1 0 2 2 2 1 0 0 2 2 1
 2 2 2 2 0 2 2 2 2 2 1 2 0 1 2 2 2 2 2 2 0 1 0 2 1 2 2 1 1 1 1 2 2 2 2 0 1
 2 2 2 0 2 1 2 2 2 1 2 2 2 1 2 2 2 0 1 2 1 2 2 2 2 1 2 1 1 1 0 1 2 2 2 2 0
 1 1 2 0 1 1 1 0 2 2 2 2 2 2 0 0 2 2 1 0 2 2 2 2 2 0 1 1 2 2 1 0 1 0 2 2 0
 1 2 2 2 1 2 2 2 2 2 1 2 2 0 1 0 2 0 2 2 2 2 1 2 2 2 1 1 1 2 1 2 2 2 2 0 2
 2 1 1 0 1 1 2 1 1 1 2 1 2 1 1 0 1 1 0 0 2 2 2 2 2 1 2 1 2 2 2 1 2 2 2 2 2
 2 2 2 0 2 2 2 0 1 2 2 2 2 2 1 2 2

In [8]:


# Combine datasets
X_combined = np.concatenate((X_labeled, X_unlabeled), axis=0)
# Y_combined = np.concatenate((y_labeled_one_hot, pseudo_labels_one_hot), axis=0)

# Check shapes
print("Shape of X_combined:", X_combined.shape)
# print("Shape of Y_combined:", Y_combined.shape)




Shape of X_combined: (24309, 224, 224, 3)


In [9]:
print("Shape of X_combined:", X_combined.shape)
print("ylabelshape",y_labeled.shape)
print("pseudo_labels shape",pseudo_labels.shape)

Shape of X_combined: (24309, 224, 224, 3)
ylabelshape (12154, 3)
pseudo_labels shape (12155,)


In [10]:
import numpy as np
from tensorflow.keras.utils import to_categorical

# Ensure pseudo_labels is 1D before one-hot encoding
pseudo_labels = np.array(pseudo_labels).reshape(-1)  # Shape (M,)

# Manually set the number of classes
num_classes = 3  # Since it's a 3-class problem

# Convert only pseudo_labels to one-hot encoding
pseudo_labels_one_hot = to_categorical(pseudo_labels, num_classes=num_classes)  # Shape (M, num_classes)

# Check the shapes
print("y_labeled shape (already one-hot):", y_labeled.shape)  # Expected: (12154, 3)
print("pseudo_labels_one_hot shape:", pseudo_labels_one_hot.shape)  # Expected: (12155, 3)

# Combine datasets
Y_combined = np.concatenate((y_labeled, pseudo_labels_one_hot), axis=0)

print("Shape of X_combined:", X_combined.shape)  # Expected: (24309, 224, 224, 3)
print("Shape of Y_combined:", Y_combined.shape)  # Expected: (24309, 3)


y_labeled shape (already one-hot): (12154, 3)
pseudo_labels_one_hot shape: (12155, 3)
Shape of X_combined: (24309, 224, 224, 3)
Shape of Y_combined: (24309, 3)


In [11]:
import numpy as np

# Save all arrays in a single file
np.savez("data_storage.npz", 
         pseudo_labels=pseudo_labels, 
         Y_combined=Y_combined, 
         X_combined=X_combined, 
         predictions=predictions)

print("All arrays saved successfully!")


All arrays saved successfully!


In [ ]:
data = np.load("data_storage.npz")
pseudo_labels = data["pseudo_labels"]
Y_combined = data["Y_combined"]
X_combined = data["X_combined"]
predictions = data["predictions"]


In [1]:
print("X_labeled shape:", X_labeled.shape)
print("y_labeled_one_hot shape:", y_labeled_one_hot.shape)
print("X_unlabeled shape:", X_unlabeled.shape)
print("pseudo_labels_one_hot shape:", pseudo_labels_one_hot.shape)


NameError: name 'X_labeled' is not defined

In [28]:
# Hyperparameters
T1 = 5     # Start pseudo-label weighting at epoch 5
T2 = 10    # Full pseudo-label weight applied at epoch 10
alpha_f = 3.0  # Final weight

def combined_loss(y_true, y_pred, epoch):
    """
    Custom loss function with gradually increasing pseudo-label weight.
    """
    labeled_mask = tf.cast(tf.reduce_max(y_true, axis=-1) > 0, tf.float32)  # 1 for labeled data, 0 for pseudo-labels
    unlabeled_mask = 1 - labeled_mask  # 1 for pseudo-labels, 0 for labeled data

    alpha_t = tf.cond(
        tf.less(epoch, T1),
        lambda: 0.0,
        lambda: tf.cond(
            tf.less(epoch, T2),
            lambda: ((epoch - T1) / (T2 - T1)) * alpha_f,
            lambda: alpha_f
        )
    )

    # Compute losses
    loss_labeled = SparseCategoricalCrossentropy()(y_true, y_pred) * labeled_mask
    loss_unlabeled = SparseCategoricalCrossentropy()(y_true, y_pred) * unlabeled_mask * alpha_t

    return tf.reduce_mean(loss_labeled + loss_unlabeled)


In [ ]:
import numpy as np
import tensorflow as tf
import time
from tensorflow.keras.optimizers import Adam

class CustomLossCallback(tf.keras.callbacks.Callback):
    """
    Updates the loss function dynamically based on the epoch.
    """
    def on_epoch_begin(self, epoch, logs=None):
        global custom_loss
        custom_loss = lambda y_true, y_pred: combined_loss(y_true, y_pred, epoch)

class EpochTimeCallback(tf.keras.callbacks.Callback):
    """
    Measures and displays the time taken for each epoch.
    """
    def on_epoch_begin(self, epoch, logs=None):
        self.start_time = time.time()
        print(f"\nEpoch {epoch + 1}/{self.params['epochs']} started...")

    def on_epoch_end(self, epoch, logs=None):
        end_time = time.time()
        elapsed_time = end_time - self.start_time
        print(f"Epoch {epoch + 1} completed in {elapsed_time:.2f} seconds.")

# Clone and recompile the model
new_model = tf.keras.models.clone_model(model)
new_model.set_weights(model.get_weights())

# Compile with custom loss
new_model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss=lambda y_true, y_pred: combined_loss(y_true, y_pred, 0),  # Initial epoch loss
    metrics=["accuracy"]
)

# Train
epochs = 15
batch_size = 32
history = new_model.fit(
    X_combined, Y_combined,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1,
    callbacks=[CustomLossCallback(), EpochTimeCallback()]
)

# Save model
new_model.save("retrained_model.h5")



In [ ]:
plt.figure(figsize=(8, 5))
num_pseudo_labels = len(X_unlabeled)
plt.plot(range(epochs), [min(epoch / T2, 1) * num_pseudo_labels for epoch in range(epochs)], label="Pseudo-labels used")
plt.xlabel("Epochs")
plt.ylabel("Pseudo-labels selected")
plt.title("Number of pseudo-labels selected over training")
plt.legend()
plt.show()
