In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.utils import to_categorical

2025-04-10 14:01:29.730587: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-10 14:01:30.639633: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1744293690.904150  285858 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744293691.009189  285858 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1744293691.649381  285858 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # Disable GPU

import tensorflow as tf
print("Running on CPU:", tf.config.list_physical_devices('GPU'))

Running on CPU: []


2025-04-10 14:01:52.876164: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2025-04-10 14:01:52.876192: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:167] env: CUDA_VISIBLE_DEVICES="-1"
2025-04-10 14:01:52.876202: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:170] CUDA_VISIBLE_DEVICES is set to -1 - this hides all GPUs from CUDA
2025-04-10 14:01:52.876206: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:178] verbose logging is disabled. Rerun with verbose logging (usually --v=1 or --vmodule=cuda_diagnostics=1) to get more diagnostic output from this module
2025-04-10 14:01:52.876211: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:183] retrieving CUDA diagnostic information for host: hela
2025-04-10 14:01:52.876214: I external/local_xla/xla/stream_executor/cuda/cuda_dia

In [ ]:
# import numpy as np

# # Load the memory-mapped dataset
# X_labeled = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/CS230Project/task2_damage_state_1/task2_X_train.npy", mmap_mode='r')
# y_labeled = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/CS230Project/task2_damage_state_1/task2_y_train.npy", mmap_mode='r')

# # Reduce the dataset size (take first half)
# num_samples = X_labeled.shape[0] // 2  # Half the dataset
# X_labeled_small = X_labeled[:num_samples]
# y_labeled_small = y_labeled[:num_samples]

# # Save the smaller dataset
# np.save("task2_X_train_half.npy", X_labeled_small)
# np.save("task2_y_train_half.npy", y_labeled_small)

# print("Reduced dataset saved as 'task2_X_train_half.npy' and 'task2_y_train_half.npy'")

# X_unlabeled_small = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/CS230Project/Task_1_scene_level/X_unlabeled_small.npy",mmap_mode='r')

Reduced dataset saved as 'task2_X_train_half.npy' and 'task2_y_train_half.npy'


In [4]:
X_labeled_small=np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/task2_damage_state_1/task2_X_train_half.npy",mmap_mode='r')
y_labeled_small=np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/task2_damage_state_1/task2_y_train_half.npy",mmap_mode='r')
print("Xshape",X_labeled_small.shape)
print("yshape",y_labeled_small.shape)

Xshape (5905, 224, 224, 3)
yshape (5905, 2)


In [6]:
model = load_model("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/VGG16/Models/vgg16_modelDamage.h5")

In [7]:
X_unlabeled_medium = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/Task_1_scene_level/X_unlabelled_medium.npy",mmap_mode='r')

In [8]:
# Get predictions
predictions = model.predict(X_unlabeled_medium)


print("First 5 predictions (raw probabilities):")
print(predictions[:5])

# Convert to pseudo-labels
pseudo_labels = np.argmax(predictions, axis=1)

# Display first 5 pseudo-labels
print("First 5 pseudo-labels (predicted class indices):")
print(pseudo_labels[:5])


250/250 ━━━━━━━━━━━━━━━━━━━━ 139s 551ms/step
First 5 predictions (raw probabilities):
[[8.449707e-24 1.000000e+00]
 [5.471038e-12 1.000000e+00]
 [1.000000e+00 7.005111e-23]
 [0.000000e+00 1.000000e+00]
 [0.000000e+00 1.000000e+00]]
First 5 pseudo-labels (predicted class indices):
[1 1 0 1 1]


In [9]:
print("First 5 predictions (raw probabilities):")
print(predictions[1000:1500])

# Convert to pseudo-labels
pseudo_labels = np.argmax(predictions, axis=1)

# Display first 5 pseudo-labels
print("First 5 pseudo-labels (predicted class indices):")
print(pseudo_labels[1000:1500])

First 5 predictions (raw probabilities):
[[0.00000000e+00 1.00000000e+00]
 [9.95994210e-01 4.00579907e-03]
 [1.00000000e+00 1.16275889e-14]
 [0.00000000e+00 1.00000000e+00]
 [1.00000000e+00 3.76493169e-22]
 [1.00000000e+00 3.90652815e-13]
 [1.00000000e+00 2.29819334e-14]
 [0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [1.00000000e+00 2.17476019e-19]
 [6.80384707e-30 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [9.19591240e-35 1.00000000e+00]
 [9.99997139e-01 2.81645907e-06]
 [9.99999762e-01 2.87327452e-07]
 [1.78672150e-01 8.21327806e-01]
 [2.10577053e-13 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [1.46486756e-20 1.00000000e+00]
 [9.77624893e-01 2.23751068e-02]
 [1.63629211e-28 1.00000000e+00]
 [1.00000000e+00 5.46311298e-08]
 [1.31090998e-30 1.00000000e+00]
 [5.96306815e-27 1.00000000e+00]
 [1.00000000e+00 2.73652688e-18]
 [3.24336381e-19 1.00000000e+00]
 [2.47548310e-33 1.00000000e+00]
 [

In [10]:
X_combined_small = np.concatenate((X_labeled_small, X_unlabeled_medium), axis=0)
# Y_combined = np.concatenate((y_labeled_one_hot, pseudo_labels_one_hot), axis=0)

# Check shapes
print("Shape of X_combined:", X_combined_small.shape)

Shape of X_combined: (13905, 224, 224, 3)


In [11]:
print("Shape of X_combined:", X_combined_small.shape)
print("ylabelshape",y_labeled_small.shape)
print("pseudo_labels shape",pseudo_labels.shape)

Shape of X_combined: (13905, 224, 224, 3)
ylabelshape (5905, 2)
pseudo_labels shape (8000,)


In [12]:
import numpy as np
from tensorflow.keras.utils import to_categorical

# Ensure pseudo_labels is 1D before one-hot encoding
pseudo_labels = np.array(pseudo_labels).reshape(-1)  # Shape (M,)


num_classes = 2  

# Convert only pseudo_labels to one-hot encoding
pseudo_labels_one_hot = to_categorical(pseudo_labels, num_classes=num_classes)  # Shape (M, num_classes)

# Check the shapes
print("y_labeled shape (already one-hot):", y_labeled_small.shape)  
print("pseudo_labels_one_hot shape:", pseudo_labels_one_hot.shape)  # Expected: (12155, 3)

# Combine datasets
Y_combined_small = np.concatenate((y_labeled_small, pseudo_labels_one_hot), axis=0)

print("Shape of X_combined:", X_combined_small.shape)  
print("Shape of Y_combined:", Y_combined_small.shape)  

y_labeled shape (already one-hot): (5905, 2)
pseudo_labels_one_hot shape: (8000, 2)
Shape of X_combined: (13905, 224, 224, 3)
Shape of Y_combined: (13905, 2)


In [13]:
from tensorflow.keras.losses import CategoricalCrossentropy

# Hyperparameters
T1 = 5     # Start pseudo-label weighting at epoch 5
T2 = 10    # Full pseudo-label weight applied at epoch 10
alpha_f = 3.0  # Final weight

def combined_loss(y_true, y_pred, epoch):
    """
    Custom loss function with gradually increasing pseudo-label weight.
    """
    labeled_mask = tf.cast(tf.reduce_max(y_true, axis=-1) > 0, tf.float32)  # 1 for labeled data, 0 for pseudo-labels
    unlabeled_mask = 1 - labeled_mask  # 1 for pseudo-labels, 0 for labeled data

    alpha_t = tf.cond(
        tf.less(epoch, T1),
        lambda: 0.0,
        lambda: tf.cond(
            tf.less(epoch, T2),
            lambda: ((epoch - T1) / (T2 - T1)) * alpha_f,
            lambda: alpha_f
        )
    )

    # Compute losses
    loss_labeled = CategoricalCrossentropy()(y_true, y_pred) * labeled_mask
    loss_unlabeled = CategoricalCrossentropy()(y_true, y_pred) * unlabeled_mask * alpha_t


    return tf.reduce_mean(loss_labeled + loss_unlabeled)


In [14]:
import numpy as np
import tensorflow as tf
import time
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import backend as K

class CustomLossCallback(tf.keras.callbacks.Callback):
    """ Updates the loss function dynamically based on the epoch. """
    def on_epoch_begin(self, epoch, logs=None):
        global custom_loss
        custom_loss = lambda y_true, y_pred: combined_loss(y_true, y_pred, epoch)

class EpochTimeCallback(tf.keras.callbacks.Callback):
    """ Measures and displays the time taken for each epoch. """
    def on_epoch_begin(self, epoch, logs=None):
        self.start_time = time.time()
        print(f"\nEpoch {epoch + 1}/{self.params['epochs']} started...")

    def on_epoch_end(self, epoch, logs=None):
        end_time = time.time()
        elapsed_time = end_time - self.start_time
        print(f"Epoch {epoch + 1} completed in {elapsed_time:.2f} seconds.")

def f1_score(y_true, y_pred):
    """ Computes the F1-score as a metric. """
    y_pred_binary = K.round(y_pred)  # Convert probabilities to binary 0/1
    tp = K.sum(K.cast(y_true * y_pred_binary, 'float'), axis=0)
    fp = K.sum(K.cast((1 - y_true) * y_pred_binary, 'float'), axis=0)
    fn = K.sum(K.cast(y_true * (1 - y_pred_binary), 'float'), axis=0)
    
    precision = tp / (tp + fp + K.epsilon())
    recall = tp / (tp + fn + K.epsilon())
    
    f1 = 2 * precision * recall / (precision + recall + K.epsilon())
    return K.mean(f1)

def confidence_score(y_true, y_pred):
    """ Computes the confidence score as the max softmax probability. """
    return K.mean(K.max(y_pred, axis=-1))

# Clone and recompile the model
new_model = tf.keras.models.clone_model(model)
new_model.set_weights(model.get_weights())

# Compile with custom metrics
new_model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss=lambda y_true, y_pred: combined_loss(y_true, y_pred, 0),  # Initial loss
    metrics=["accuracy", f1_score, confidence_score]
)

# Train
epochs = 15
batch_size = 32
history = new_model.fit(
    X_combined_small, Y_combined_small,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1,
    callbacks=[CustomLossCallback(), EpochTimeCallback()]
)

# Save model
new_model.save("retrained_model_damage_medium.h5")



Epoch 1/15 started...
Epoch 1/15
392/392 ━━━━━━━━━━━━━━━━━━━━ 0s 562ms/step - accuracy: 0.8431 - confidence_score: 0.9852 - f1_score: 0.8157 - loss: 3.1442Epoch 1 completed in 248.65 seconds.
392/392 ━━━━━━━━━━━━━━━━━━━━ 249s 630ms/step - accuracy: 0.8431 - confidence_score: 0.9852 - f1_score: 0.8156 - loss: 3.1421 - val_accuracy: 0.8562 - val_confidence_score: 0.9612 - val_f1_score: 0.8493 - val_loss: 0.7303

Epoch 2/15 started...
Epoch 2/15
391/392 ━━━━━━━━━━━━━━━━━━━━ 0s 563ms/step - accuracy: 0.8344 - confidence_score: 0.9621 - f1_score: 0.8004 - loss: 0.9682Epoch 2 completed in 244.17 seconds.
392/392 ━━━━━━━━━━━━━━━━━━━━ 244s 623ms/step - accuracy: 0.8344 - confidence_score: 0.9621 - f1_score: 0.8004 - loss: 0.9674 - val_accuracy: 0.8239 - val_confidence_score: 0.9262 - val_f1_score: 0.8176 - val_loss: 0.5564

Epoch 3/15 started...
Epoch 3/15
391/392 ━━━━━━━━━━━━━━━━━━━━ 0s 567ms/step - accuracy: 0.8409 - confidence_score: 0.9303 - f1_score: 0.8116 - loss: 0.5221Epoch 3 complete