In [ ]:
# import numpy as np
# import os
# X_unlabelled=np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/Task_1_scene_level/X_unlabeled.npy",mmap_mode='r')
# print(X_unlabelled.shape)

(12155, 224, 224, 3)


In [ ]:
# X_unlabelled_medium = X_unlabelled[:8000]

# # Save to a new .npy file
# np.save("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/Task_1_scene_level/X_unlabelled_medium.npy", X_unlabelled_medium)

# print("Saved X_unlabelled_medium with shape:", X_unlabelled_medium.shape)


Saved X_unlabelled_medium with shape: (8000, 224, 224, 3)


In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.utils import to_categorical

2025-04-09 17:00:52.971737: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-09 17:00:52.984840: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1744218052.999495  194415 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744218053.003895  194415 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1744218053.015385  194415 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # Disable GPU

import tensorflow as tf
print("Running on CPU:", tf.config.list_physical_devices('GPU'))

Running on CPU: []


2025-04-09 17:01:00.776455: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2025-04-09 17:01:00.776481: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:167] env: CUDA_VISIBLE_DEVICES="-1"
2025-04-09 17:01:00.776487: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:170] CUDA_VISIBLE_DEVICES is set to -1 - this hides all GPUs from CUDA
2025-04-09 17:01:00.776499: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:178] verbose logging is disabled. Rerun with verbose logging (usually --v=1 or --vmodule=cuda_diagnostics=1) to get more diagnostic output from this module
2025-04-09 17:01:00.776504: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:183] retrieving CUDA diagnostic information for host: hela
2025-04-09 17:01:00.776506: I external/local_xla/xla/stream_executor/cuda/cuda_dia

In [3]:
import tensorflow as tf
from tensorflow.keras.models import load_model
model = load_model("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/VGG16/Models/vgg16_modelScene_small_final.h5")

In [4]:
X_unlabelled = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/Task_1_scene_level/X_unlabelled_medium.npy", mmap_mode='r')

In [5]:
predictions = model.predict(X_unlabelled)


print("First 5 predictions (raw probabilities):")
print(predictions[:5])

# Convert to pseudo-labels
pseudo_labels = np.argmax(predictions, axis=1)

# Display first 5 pseudo-labels
print("First 5 pseudo-labels (predicted class indices):")
print(pseudo_labels[:5])

250/250 ━━━━━━━━━━━━━━━━━━━━ 165s 653ms/step
First 5 predictions (raw probabilities):
[[0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [1.5078768e-21 2.0557606e-15 1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]
First 5 pseudo-labels (predicted class indices):
[2 2 2 2 2]


In [9]:
pseudo_labels = np.argmax(predictions, axis=1)

# Display first 5 pseudo-labels
print("First 5 pseudo-labels (predicted class indices):")
# print(pseudo_labels[1000:1500])
# print(predictions[1000:1500])

First 5 pseudo-labels (predicted class indices):


In [11]:
X_labeled_small = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/Task_1_scene_level/X_labeled_small.npy",mmap_mode='r')
y_labeled_small = np.load("/home/sombit-ng-nonadm/vaibhav_intern_pg/BTP+AIproject/Task_1_scene_level/y_labeled_small.npy",mmap_mode='r')

In [14]:
X_combined = np.concatenate((X_labeled_small, X_unlabelled), axis=0)
# Y_combined = np.concatenate((y_labeled_one_hot, pseudo_labels_one_hot), axis=0)

# Check shapes
print("Shape of X_combined:", X_combined_small.shape)

Shape of X_combined: (12051, 224, 224, 3)


In [15]:
print("Shape of X_combined:", X_combined.shape)
print("ylabelshape",y_labeled_small.shape)
print("pseudo_labels shape",pseudo_labels.shape)

Shape of X_combined: (12051, 224, 224, 3)
ylabelshape (4051, 3)
pseudo_labels shape (8000,)


In [16]:
import numpy as np
from tensorflow.keras.utils import to_categorical

# Ensure pseudo_labels is 1D before one-hot encoding
pseudo_labels = np.array(pseudo_labels).reshape(-1)  # Shape (M,)

# Manually set the number of classes
num_classes = 3  # Since it's a 3-class problem

# Convert only pseudo_labels to one-hot encoding
pseudo_labels_one_hot = to_categorical(pseudo_labels, num_classes=num_classes)  # Shape (M, num_classes)

# Check the shapes
print("y_labeled shape (already one-hot):", y_labeled_small.shape)  # Expected: (12154, 3)
print("pseudo_labels_one_hot shape:", pseudo_labels_one_hot.shape)  # Expected: (12155, 3)

# Combine datasets
Y_combined_small = np.concatenate((y_labeled_small, pseudo_labels_one_hot), axis=0)

print("Shape of X_combined:", X_combined_small.shape)  # Expected: (24309, 224, 224, 3)
print("Shape of Y_combined:", Y_combined_small.shape) 

y_labeled shape (already one-hot): (4051, 3)
pseudo_labels_one_hot shape: (8000, 3)
Shape of X_combined: (12051, 224, 224, 3)
Shape of Y_combined: (12051, 3)


In [17]:
from tensorflow.keras.losses import CategoricalCrossentropy

# Hyperparameters
T1 = 5     # Start pseudo-label weighting at epoch 5
T2 = 10    # Full pseudo-label weight applied at epoch 10
alpha_f = 3.0  # Final weight

def combined_loss(y_true, y_pred, epoch):
    """
    Custom loss function with gradually increasing pseudo-label weight.
    """
    labeled_mask = tf.cast(tf.reduce_max(y_true, axis=-1) > 0, tf.float32)  # 1 for labeled data, 0 for pseudo-labels
    unlabeled_mask = 1 - labeled_mask  # 1 for pseudo-labels, 0 for labeled data

    alpha_t = tf.cond(
        tf.less(epoch, T1),
        lambda: 0.0,
        lambda: tf.cond(
            tf.less(epoch, T2),
            lambda: ((epoch - T1) / (T2 - T1)) * alpha_f,
            lambda: alpha_f
        )
    )

    # Compute losses
    loss_labeled = CategoricalCrossentropy()(y_true, y_pred) * labeled_mask
    loss_unlabeled = CategoricalCrossentropy()(y_true, y_pred) * unlabeled_mask * alpha_t


    return tf.reduce_mean(loss_labeled + loss_unlabeled)

In [18]:
import numpy as np
import tensorflow as tf
import time
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import backend as K

class CustomLossCallback(tf.keras.callbacks.Callback):
    """ Updates the loss function dynamically based on the epoch. """
    def on_epoch_begin(self, epoch, logs=None):
        global custom_loss
        custom_loss = lambda y_true, y_pred: combined_loss(y_true, y_pred, epoch)

class EpochTimeCallback(tf.keras.callbacks.Callback):
    """ Measures and displays the time taken for each epoch. """
    def on_epoch_begin(self, epoch, logs=None):
        self.start_time = time.time()
        print(f"\nEpoch {epoch + 1}/{self.params['epochs']} started...")

    def on_epoch_end(self, epoch, logs=None):
        end_time = time.time()
        elapsed_time = end_time - self.start_time
        print(f"Epoch {epoch + 1} completed in {elapsed_time:.2f} seconds.")

def f1_score(y_true, y_pred):
    """ Computes the F1-score as a metric. """
    y_pred_binary = K.round(y_pred)  # Convert probabilities to binary 0/1
    tp = K.sum(K.cast(y_true * y_pred_binary, 'float'), axis=0)
    fp = K.sum(K.cast((1 - y_true) * y_pred_binary, 'float'), axis=0)
    fn = K.sum(K.cast(y_true * (1 - y_pred_binary), 'float'), axis=0)
    
    precision = tp / (tp + fp + K.epsilon())
    recall = tp / (tp + fn + K.epsilon())
    
    f1 = 2 * precision * recall / (precision + recall + K.epsilon())
    return K.mean(f1)

def confidence_score(y_true, y_pred):
    """ Computes the confidence score as the max softmax probability. """
    return K.mean(K.max(y_pred, axis=-1))

# Clone and recompile the model
new_model = tf.keras.models.clone_model(model)
new_model.set_weights(model.get_weights())

# Compile with custom metrics
new_model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss=lambda y_true, y_pred: combined_loss(y_true, y_pred, 0),  # Initial loss
    metrics=["accuracy", f1_score, confidence_score]
)

# Train
epochs = 15
batch_size = 32
history = new_model.fit(
    X_combined_small, Y_combined_small,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1,
    callbacks=[CustomLossCallback(), EpochTimeCallback()]
)

# Save model
new_model.save("retrained_model_medium.h5")



Epoch 1/15 started...
Epoch 1/15
339/339 ━━━━━━━━━━━━━━━━━━━━ 0s 644ms/step - accuracy: 0.7928 - confidence_score: 0.9848 - f1_score: 0.7413 - loss: 4.9012Epoch 1 completed in 245.76 seconds.
339/339 ━━━━━━━━━━━━━━━━━━━━ 246s 720ms/step - accuracy: 0.7928 - confidence_score: 0.9848 - f1_score: 0.7413 - loss: 4.8988 - val_accuracy: 0.8798 - val_confidence_score: 0.9767 - val_f1_score: 0.8041 - val_loss: 0.5558

Epoch 2/15 started...
Epoch 2/15
339/339 ━━━━━━━━━━━━━━━━━━━━ 0s 671ms/step - accuracy: 0.7829 - confidence_score: 0.9714 - f1_score: 0.7268 - loss: 2.3150Epoch 2 completed in 253.80 seconds.
339/339 ━━━━━━━━━━━━━━━━━━━━ 254s 749ms/step - accuracy: 0.7829 - confidence_score: 0.9714 - f1_score: 0.7268 - loss: 2.3140 - val_accuracy: 0.8308 - val_confidence_score: 0.9481 - val_f1_score: 0.7611 - val_loss: 0.5855

Epoch 3/15 started...
Epoch 3/15
339/339 ━━━━━━━━━━━━━━━━━━━━ 0s 666ms/step - accuracy: 0.7800 - confidence_score: 0.9431 - f1_score: 0.7304 - loss: 1.2044Epoch 3 complete